import { SubtitleYesCaptionWrapper } from ".";

export default {
  title: "Components/SubtitleYesCaptionWrapper",
  component: SubtitleYesCaptionWrapper,
  argTypes: {
    resolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    subtitle: true,
    caption: true,
    resolution: "desktop",
    className: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionText: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionDivClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionDivClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionText1: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText2: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionText3: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionFrameWrapperClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionText4: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionText5: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionText6: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionText7: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName1: {},
    resoolutionDesktopWrapperGraphBarCaptionText8: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionFrameWrapperClassNameOverride: {},
    resoolutionDesktopWrapperResoolutionDesktopClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName1: {},
    resoolutionDesktopWrapperGraphBarCaptionText9: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionText10: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText11: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText12: "39.2%",
    resoolutionDesktopWrapperVisible: true,
    resoolutionDesktopWrapperGraphBarCaptionText13: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName2: {},
    resoolutionDesktopWrapperGraphBarCaptionText14: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName3: {},
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName2: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName4: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName5: {},
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName3: {},
    resoolutionDesktopWrapperGraphBarCaptionText15: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText16: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName4: {},
    resoolutionDesktopWrapperGraphBarCaptionText17: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassName1: {},
    resoolutionDesktopWrapperVisible1: true,
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassName2: {},
    resoolutionDesktopWrapperGraphBarCaptionColumns: "two",
    resoolutionDesktopWrapperGraphBarCaptionColumns1: "two",
    resoolutionDesktopWrapperVisible2: true,
    resoolutionDesktopWrapperVisible3: true,
    resoolutionDesktopWrapperVisible4: true,
    resoolutionDesktopWrapperVisible5: true,
    resoolutionDesktopWrapperVisible6: true,
    resoolutionDesktopWrapperVisible7: true,
    text: "*American Community Survey (ACS) Census Bureau<br/>** Total percentages may vary by 1% due to rounding",
    hasSectionTitle: true,
    resoolutionDesktopWrapperGraphBarCaptionColumns2: "two",
    resoolutionDesktopWrapperGraphBarCaptionColumns3: "two",
    resoolutionDesktopWrapperVisible8: true,
    hasFrame: true,
    resoolutionDesktopWrapperGraphBarCaptionColumns4: "two",
    resoolutionDesktopWrapperGraphBarCaptionColumns5: "two",
    sectionTitleClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName6: {},
  },
};
