import { SubtitleYesCaptionWrapper } from ".";

export default {
  title: "Components/SubtitleYesCaptionWrapper",
  component: SubtitleYesCaptionWrapper,
  argTypes: {
    resolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    subtitle: true,
    caption: true,
    resolution: "desktop",
    className: {},
    resoolutionDesktopWrapperGraphBarCaptionText: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionText1: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionText2: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionText3: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText4: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionText5: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionDivClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionDivClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionText6: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionFrameWrapperClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionText7: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionFrameWrapperClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName1: {},
    resoolutionDesktopWrapperGraphBarCaptionText8: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionText9: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName1: {},
    resoolutionDesktopWrapperGraphBarCaptionText10: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName2: {},
    resoolutionDesktopWrapperGraphBarCaptionText11: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName3: {},
    resoolutionDesktopWrapperGraphBarCaptionText12: "39.2%",
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName2: {},
    resoolutionDesktopWrapperGraphBarCaptionText13: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText14: "39.2%",
    resoolutionDesktopWrapperVisible: true,
    resoolutionDesktopWrapperResoolutionDesktopClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName3: {},
    resoolutionDesktopWrapperGraphBarCaptionText15: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionText16: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName4: {},
    resoolutionDesktopWrapperGraphBarCaptionText17: "Transportation",
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName5: {},
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassName: {},
    resoolutionDesktopWrapperGraphBarCaptionRectangleClassName4: {},
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassNameOverride: {},
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassName1: {},
    resoolutionDesktopWrapperVisible1: true,
    resoolutionDesktopWrapperGraphBarCaptionSectionTitleClassName2: {},
    resoolutionDesktopWrapperGraphBarCaptionColumnsResolutionClassName6: {},
    sectionTitleClassName: {},
  },
};
