version: '3'

services:
  react-app:
    build: .
    container_name: WTC-Bay-Annual-Report
    command: npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "1234:1234"
    environment:
      NODE_ENV: development

volumes:
  node_modules: