import { ResoolutionDesktopWrapper } from ".";

export default {
  title: "Components/ResoolutionDesktopWrapper",
  component: ResoolutionDesktopWrapper,
  argTypes: {
    resoolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    resoolution: "desktop",
    className: {},
    graphBarCaptionColumnsResolutionClassName: {},
    graphBarCaptionRectangleClassName: {},
    graphBarCaptionText: "39.2%",
    graphBarCaptionColumnsResolutionClassNameOverride: {},
    graphBarCaptionRectangleClassNameOverride: {},
    graphBarCaptionText1: "Transportation",
    graphBarCaptionSectionTitleClassName: {},
    graphBarCaptionText2: "39.2%",
    graphBarCaptionFrameWrapperClassName: {},
    graphBarCaptionDivClassName: {},
    graphBarCaptionText3: "Transportation",
    graphBarCaptionText4: "39.2%",
    graphBarCaptionFrameWrapperClassNameOverride: {},
    graphBarCaptionDivClassNameOverride: {},
    graphBarCaptionText5: "Transportation",
    graphBarCaptionText6: "39.2%",
    graphBarCaptionColumnsResolutionClassName1: {},
    graphBarCaptionRectangleClassName1: {},
    graphBarCaptionText7: "Transportation",
    graphBarCaptionSectionTitleClassNameOverride: {},
    graphBarCaptionText8: "39.2%",
    graphBarCaptionColumnsResolutionClassName2: {},
    graphBarCaptionRectangleClassName2: {},
    graphBarCaptionText9: "Transportation",
    graphBarCaptionText10: "39.2%",
    graphBarCaptionColumnsResolutionClassName3: {},
    graphBarCaptionRectangleClassName3: {},
    graphBarCaptionText11: "Transportation",
    graphBarCaptionText12: "39.2%",
    graphBarCaptionColumnsResolutionClassName4: {},
    graphBarCaptionText13: "Transportation",
    graphBarCaptionText14: "39.2%",
    visible: true,
    visible1: true,
    graphBarCaptionText15: "Transportation",
    graphBarCaptionSectionTitleClassName1: {},
    graphBarCaptionColumnsResolutionClassName5: {},
    graphBarCaptionRectangleClassName4: {},
    graphBarCaptionText16: "Transportation",
    graphBarCaptionText17: "39.2%",
    graphBarCaptionSectionTitleClassName2: {},
    graphBarCaptionColumnsResolutionClassName6: {},
  },
};
