import { GraphChart } from ".";

export default {
  title: "Components/GraphChart",
  component: GraphChart,
  argTypes: {
    quantity: {
      options: ["two", "one"],
      control: { type: "select" },
    },
    resolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    quantity: "two",
    resolution: "desktop",
    className: {},
    visible: true,
    sectionTitleClassName: {},
    text: "Number of Source Tests in 2022",
    hasFrame: true,
    hasGroup: true,
    graphChartLineSectionTitleClassName: {},
    graphChartLineText: "Refinery Source Tests",
    graphChartLineText1: "49.0%",
    graphChartLineLines: "two",
    graphChartLineColumns: "three",
    graphChartLineFrameClassName: {},
    graphChartLineSectionTitleClassNameOverride: {},
    graphChartLineText2: "Refinery Source Tests",
    graphChartLineText3: "49.0%",
    graphChartLineLines1: "two",
    graphChartLineColumns1: "three",
    graphChartLineFrameClassNameOverride: {},
    graphChartLineDivClassName: {},
    graphChartLineText4: "Refinery Source Tests",
    graphChartLineText5: "49.0%",
    graphChartLineLines2: "two",
    graphChartLineColumns2: "three",
    graphChartLineFrameWrapperClassName: {},
    graphChartLineDivClassNameOverride: {},
    graphChartLineText6: "Refinery Source Tests",
    graphChartLineText7: "49.0%",
    graphChartLineLines3: "two",
    graphChartLineColumns3: "three",
    graphChartLineFrameWrapperClassNameOverride: {},
    visible1: true,
    visible2: true,
    visible3: true,
    visible4: true,
    visible5: true,
    visible6: true,
    graphChartTotalGraphChartLineText: "abc",
    graphChartTotalGraphChartLineSectionTitleClassName: {},
    graphChartTotalGraphChartLineSectionTitleClassNameOverride: {},
    graphChartTotalGraphChartLineGraphChartLineClassName: {},
    graphChartTotalGraphChartLineHasFrame: true,
    graphChartTotalGraphChartLineText1: "abc",
    graphChartTotalGraphChartLineColumns: "abc",
    graphChartTotalLinesResolutionClassName: {},
    graphChartTotalLines: "three",
    sectionTitleClassNameOverride: {},
    text1:
      "*Samples provide information about pollutant levels in ambient air, which helps to identify areas for further reductions.",
    visible7: true,
    groupClassName: {},
    divClassName: {},
    hasGroupWrapper: true,
    hasDiv: true,
    graphChartLineText8: "Refinery Source Tests",
    graphChartLineText9: "49.0%",
    graphChartLineLines4: "two",
    graphChartLineColumns4: "three",
    graphChartLineText10: "Refinery Source Tests",
    graphChartLineText11: "49.0%",
    graphChartLineLines5: "two",
    graphChartLineColumns5: "three",
    graphChartLineText12: "Refinery Source Tests",
    graphChartLineText13: "49.0%",
    graphChartLineLines6: "two",
    graphChartLineColumns6: "three",
    visible8: true,
    visible9: true,
    visible10: true,
    visible11: true,
    visible12: true,
    visible13: true,
    visible14: true,
    visible15: true,
    hasSectionTitleWrapper: true,
    visible16: true,
    groupClassNameOverride: {},
    divClassNameOverride: {},
    hasFrame1: true,
    hasGroup1: true,
    graphChartLineSectionTitleClassName1: {},
    graphChartLineText14: "Refinery Source Tests",
    graphChartLineText15: "49.0%",
    graphChartLineLines7: "two",
    graphChartLineColumns7: "three",
    graphChartLineSectionTitleClassName2: {},
    graphChartLineText16: "Refinery Source Tests",
    graphChartLineText17: "49.0%",
    graphChartLineLines8: "two",
    graphChartLineColumns8: "three",
    graphChartLineSectionTitleClassName3: {},
    graphChartLineText18: "Refinery Source Tests",
    graphChartLineText19: "49.0%",
    graphChartLineLines9: "two",
    graphChartLineColumns9: "three",
    visible17: true,
    visible18: true,
    visible19: true,
    visible20: true,
    visible21: true,
    visible22: true,
    visible23: true,
    visible24: true,
    frameClassName: {},
    visible25: true,
    frameClassNameOverride: {},
    sectionTitleWrapperClassName: {},
    sectionTitleClassName1: {},
    hasFrame2: true,
    hasGroup2: true,
    graphChartLineSectionTitleClassName4: {},
    graphChartLineText20: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName: {},
    graphChartLineText21: "49.0%",
    graphChartLineGraphChartLineClassName: {},
    graphChartLineLines10: "two",
    graphChartLineColumns10: "three",
    graphChartLineFrameClassName1: {},
    graphChartLineSectionTitleClassName5: {},
    graphChartLineText22: "Refinery Source Tests",
    graphChartLineLinesColumnsClassNameOverride: {},
    graphChartLineText23: "49.0%",
    graphChartLineGraphChartLineClassNameOverride: {},
    graphChartLineLines11: "two",
    graphChartLineColumns11: "three",
    graphChartLineFrameClassName2: {},
    graphChartLineSectionTitleClassName6: {},
    graphChartLineText24: "Refinery Source Tests",
    graphChartLineGraphChartLineWrapperClassName: {},
    graphChartLineText25: "49.0%",
    graphChartLineGraphChartLineClassName1: {},
    graphChartLineLines12: "two",
    graphChartLineColumns12: "three",
    graphChartLineFrameClassName3: {},
    graphChartLineSectionTitleClassName7: {},
    graphChartLineText26: "Refinery Source Tests",
    graphChartLineGraphChartLineWrapperClassNameOverride: {},
    graphChartLineText27: "49.0%",
    graphChartLineGraphChartLineClassName2: {},
    graphChartLineLines13: "two",
    graphChartLineColumns13: "three",
    graphChartLineFrameClassName4: {},
    visible26: true,
    visible27: true,
    visible28: true,
    visible29: true,
    visible30: true,
    visible31: true,
    graphChartTotalGraphChartLineText2: "abc",
    graphChartTotalGraphChartLineFrameClassName: {},
    graphChartTotalGraphChartLineGraphChartLineClassNameOverride: {},
    graphChartTotalGraphChartLineColumns1: "abc",
    graphChartTotalLinesResolutionClassNameOverride: {},
    graphChartTotalGraphChartLineDivClassName: {},
    graphChartTotalLines1: "three",
    graphChartTotalGraphChartLineLinesColumnsClassName: {},
    sectionTitleWrapperClassNameOverride: {},
    sectionTitleClassName2: {},
    frameClassName1: {},
    visible32: true,
    groupWrapperClassName: {},
    groupClassName1: {},
    sectionTitleClassName3: {},
    hasFrame3: true,
    hasGroup3: true,
    graphChartLineText28: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName1: {},
    graphChartLineGraphChartLineClassName3: {},
    graphChartLineLines14: "two",
    graphChartLineColumns14: "three",
    graphChartLineResolution: "desktop",
    graphChartLineFrameClassName5: {},
    graphChartLineSectionTitleWrapperClassName: {},
    graphChartLineText29: "Refinery Source Tests",
    graphChartLineText30: "abc",
    graphChartLineLinesColumnsClassName2: {},
    graphChartLineGraphChartLineClassName4: {},
    graphChartLineLines15: "two",
    graphChartLineColumns15: "three",
    graphChartLineResolution1: "desktop",
    graphChartLineFrameClassName6: {},
    graphChartLineText31: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName3: {},
    graphChartLineText32: "abc",
    graphChartLineGraphChartLineClassName5: {},
    graphChartLineLines16: "two",
    graphChartLineColumns16: "three",
    graphChartLineResolution2: "desktop",
    graphChartLineFrameClassName7: {},
    visible33: true,
    visible34: true,
    visible35: true,
    visible36: true,
    visible37: true,
    visible38: true,
    visible39: true,
    visible40: true,
    hasFrame4: true,
    frameClassName2: {},
    visible41: true,
    groupWrapperClassNameOverride: {},
    groupClassName2: {},
    sectionTitleClassName4: {},
    hasFrame5: true,
    hasGroup4: true,
    graphChartLineSectionTitleClassName8: {},
    graphChartLineText33: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName4: {},
    graphChartLineText34: "abc",
    graphChartLineGraphChartLineClassName6: {},
    graphChartLineLines17: "two",
    graphChartLineColumns17: "three",
    graphChartLineResolution3: "desktop",
    graphChartLineFrameClassName8: {},
    graphChartLineSectionTitleClassName9: {},
    graphChartLineText35: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName5: {},
    graphChartLineText36: "abc",
    graphChartLineGraphChartLineClassName7: {},
    graphChartLineLines18: "two",
    graphChartLineColumns18: "three",
    graphChartLineResolution4: "desktop",
    graphChartLineSectionTitleClassName10: {},
    graphChartLineSectionTitleWrapperClassNameOverride: {},
    graphChartLineText37: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName6: {},
    graphChartLineText38: "abc",
    graphChartLineGraphChartLineClassName8: {},
    graphChartLineLines19: "two",
    graphChartLineColumns19: "three",
    graphChartLineResolution5: "desktop",
    graphChartLineFrameClassName9: {},
    visible42: true,
    visible43: true,
    visible44: true,
    visible45: true,
    visible46: true,
    visible47: true,
    visible48: true,
    visible49: true,
    graphChartLineText39: "abc",
  },
};
