import { GraphChart } from ".";

export default {
  title: "Components/GraphChart",
  component: GraphChart,
  argTypes: {
    quantity: {
      options: ["two", "one"],
      control: { type: "select" },
    },
    resolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    quantity: "two",
    resolution: "desktop",
    className: {},
    visible: true,
    groupClassName: {},
    sectionTitleClassName: {},
    text: "Number of Source Tests in 2022",
    hasFrame: true,
    hasGroup: true,
    graphChartLineText: "49.0%",
    graphChartLineText1: "Refinery Source Tests",
    graphChartLineFrameClassName: {},
    graphChartLineLines: "two",
    graphChartLineColumns: "three",
    graphChartLineSectionTitleClassName: {},
    graphChartLineText2: "49.0%",
    graphChartLineText3: "Refinery Source Tests",
    graphChartLineFrameClassNameOverride: {},
    graphChartLineLines1: "two",
    graphChartLineColumns1: "three",
    graphChartLineSectionTitleClassNameOverride: {},
    graphChartLineText4: "49.0%",
    graphChartLineText5: "Refinery Source Tests",
    graphChartLineFrameWrapperClassName: {},
    graphChartLineLines2: "two",
    graphChartLineColumns2: "three",
    graphChartLineDivClassName: {},
    graphChartLineText6: "49.0%",
    graphChartLineText7: "Refinery Source Tests",
    graphChartLineFrameWrapperClassNameOverride: {},
    graphChartLineLines3: "two",
    graphChartLineColumns3: "three",
    graphChartLineDivClassNameOverride: {},
    visible1: true,
    visible2: true,
    visible3: true,
    visible4: true,
    visible5: true,
    visible6: true,
    graphChartTotalGraphChartLineGraphChartLineClassName: {},
    graphChartTotalGraphChartLineHasFrame: true,
    graphChartTotalGraphChartLineText: "abc",
    graphChartTotalLinesResolutionClassName: {},
    graphChartTotalGraphChartLineColumns: "abc",
    graphChartTotalLines: "three",
    graphChartTotalGraphChartLineText1: "abc",
    graphChartTotalGraphChartLineSectionTitleClassName: {},
    graphChartTotalGraphChartLineSectionTitleClassNameOverride: {},
    sectionTitleClassNameOverride: {},
    text1:
      "*Samples provide information about pollutant levels in ambient air, which helps to identify areas for further reductions.",
    visible7: true,
    groupClassNameOverride: {},
    divClassName: {},
    hasGroupWrapper: true,
    hasDiv: true,
    graphChartLineText8: "Refinery Source Tests",
    graphChartLineLines4: "two",
    graphChartLineColumns4: "three",
    graphChartLineText9: "49.0%",
    graphChartLineText10: "Refinery Source Tests",
    graphChartLineLines5: "two",
    graphChartLineColumns5: "three",
    graphChartLineText11: "49.0%",
    graphChartLineText12: "Refinery Source Tests",
    graphChartLineLines6: "two",
    graphChartLineColumns6: "three",
    graphChartLineText13: "49.0%",
    visible8: true,
    visible9: true,
    visible10: true,
    visible11: true,
    visible12: true,
    visible13: true,
    visible14: true,
    visible15: true,
    hasSectionTitleWrapper: true,
    visible16: true,
    sectionTitleWrapperClassName: {},
    divClassNameOverride: {},
    hasFrame1: true,
    hasGroup1: true,
    graphChartLineText14: "49.0%",
    graphChartLineText15: "Refinery Source Tests",
    graphChartLineLines7: "two",
    graphChartLineColumns7: "three",
    graphChartLineSectionTitleClassName1: {},
    graphChartLineText16: "49.0%",
    graphChartLineText17: "Refinery Source Tests",
    graphChartLineLines8: "two",
    graphChartLineColumns8: "three",
    graphChartLineSectionTitleClassName2: {},
    graphChartLineText18: "49.0%",
    graphChartLineText19: "Refinery Source Tests",
    graphChartLineLines9: "two",
    graphChartLineColumns9: "three",
    graphChartLineSectionTitleClassName3: {},
    visible17: true,
    visible18: true,
    visible19: true,
    visible20: true,
    visible21: true,
    visible22: true,
    visible23: true,
    visible24: true,
    frameClassName: {},
    visible25: true,
    sectionTitleWrapperClassNameOverride: {},
    sectionTitleClassName1: {},
    hasFrame2: true,
    hasGroup2: true,
    graphChartLineText20: "49.0%",
    graphChartLineText21: "Refinery Source Tests",
    graphChartLineFrameClassName1: {},
    graphChartLineLines10: "two",
    graphChartLineColumns10: "three",
    graphChartLineSectionTitleClassName4: {},
    graphChartLineText22: "49.0%",
    graphChartLineText23: "Refinery Source Tests",
    graphChartLineFrameClassName2: {},
    graphChartLineLines11: "two",
    graphChartLineColumns11: "three",
    graphChartLineSectionTitleClassName5: {},
    graphChartLineText24: "49.0%",
    graphChartLineText25: "Refinery Source Tests",
    graphChartLineFrameClassName3: {},
    graphChartLineLines12: "two",
    graphChartLineColumns12: "three",
    graphChartLineSectionTitleClassName6: {},
    graphChartLineText26: "49.0%",
    graphChartLineText27: "Refinery Source Tests",
    graphChartLineFrameClassName4: {},
    graphChartLineLines13: "two",
    graphChartLineColumns13: "three",
    graphChartLineSectionTitleClassName7: {},
    visible26: true,
    visible27: true,
    visible28: true,
    visible29: true,
    visible30: true,
    visible31: true,
    graphChartTotalGraphChartLineDivClassName: {},
    graphChartTotalGraphChartLineText2: "abc",
    graphChartTotalLinesResolutionClassNameOverride: {},
    graphChartTotalLines1: "three",
    graphChartTotalGraphChartLineColumns1: "abc",
    graphChartTotalGraphChartLineFrameClassName: {},
    frameClassNameOverride: {},
    sectionTitleClassName2: {},
    visible32: true,
    groupClassName1: {},
    sectionTitleClassName3: {},
    hasFrame3: true,
    hasGroup3: true,
    graphChartLineText28: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName: {},
    graphChartLineFrameClassName5: {},
    graphChartLineGraphChartLineClassName: {},
    graphChartLineLines14: "two",
    graphChartLineColumns14: "three",
    graphChartLineResolution: "desktop",
    graphChartLineText29: "abc",
    graphChartLineText30: "Refinery Source Tests",
    graphChartLineLinesColumnsClassNameOverride: {},
    graphChartLineFrameClassName6: {},
    graphChartLineGraphChartLineClassNameOverride: {},
    graphChartLineSectionTitleWrapperClassName: {},
    graphChartLineLines15: "two",
    graphChartLineColumns15: "three",
    graphChartLineResolution1: "desktop",
    graphChartLineText31: "abc",
    graphChartLineText32: "Refinery Source Tests",
    graphChartLineGraphChartLineWrapperClassName: {},
    graphChartLineFrameClassName7: {},
    graphChartLineGraphChartLineClassName1: {},
    graphChartLineLines16: "two",
    graphChartLineColumns16: "three",
    graphChartLineResolution2: "desktop",
    visible33: true,
    visible34: true,
    visible35: true,
    visible36: true,
    visible37: true,
    visible38: true,
    visible39: true,
    visible40: true,
    hasFrame4: true,
    visible41: true,
    groupClassName2: {},
    sectionTitleClassName4: {},
    hasFrame5: true,
    hasGroup4: true,
    graphChartLineText33: "abc",
    graphChartLineText34: "Refinery Source Tests",
    graphChartLineGraphChartLineWrapperClassNameOverride: {},
    graphChartLineFrameClassName8: {},
    graphChartLineGraphChartLineClassName2: {},
    graphChartLineLines17: "two",
    graphChartLineColumns17: "three",
    graphChartLineResolution3: "desktop",
    graphChartLineSectionTitleClassName8: {},
    graphChartLineText35: "abc",
    graphChartLineText36: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName1: {},
    graphChartLineGraphChartLineClassName3: {},
    graphChartLineLines18: "two",
    graphChartLineColumns18: "three",
    graphChartLineResolution4: "desktop",
    graphChartLineSectionTitleClassName9: {},
    graphChartLineText37: "abc",
    graphChartLineText38: "Refinery Source Tests",
    graphChartLineLinesColumnsClassName2: {},
    graphChartLineFrameClassName9: {},
    graphChartLineGraphChartLineClassName4: {},
    graphChartLineSectionTitleWrapperClassNameOverride: {},
    graphChartLineLines19: "two",
    graphChartLineColumns19: "three",
    graphChartLineResolution5: "desktop",
    graphChartLineSectionTitleClassName10: {},
    visible42: true,
    visible43: true,
    visible44: true,
    visible45: true,
    visible46: true,
    visible47: true,
    visible48: true,
    visible49: true,
    graphChartLineText39: "abc",
    graphChartTotalGraphChartLineFrameClassNameOverride: {},
    frameClassName1: {},
    graphChartLineText40: "Refinery Source Tests",
    graphChartLineLines20: "two",
    graphChartLineColumns20: "three",
    graphChartLineText41: "49.0%",
    graphChartLineText42: "Refinery Source Tests",
    graphChartLineLines21: "two",
    graphChartLineColumns21: "three",
    graphChartLineText43: "49.0%",
    graphChartTotalGraphChartLineText3: "abc",
    graphChartTotalGraphChartLineColumns2: "abc",
    graphChartTotalLines2: "three",
    graphChartTotalGraphChartLineDivClassNameOverride: {},
    graphChartTotalGraphChartLineText4: "abc",
    graphChartTotalGraphChartLineSectionTitleClassName1: {},
    frameClassName2: {},
    graphChartLineText44: "Refinery Source Tests",
    graphChartLineLines22: "two",
    graphChartLineColumns22: "three",
    graphChartLineText45: "49.0%",
    graphChartTotalGraphChartLineText5: "abc",
    graphChartTotalGraphChartLineColumns3: "abc",
    graphChartTotalLines3: "three",
    graphChartTotalGraphChartLineFrameClassName1: {},
    graphChartTotalGraphChartLineText6: "abc",
    graphChartTotalGraphChartLineSectionTitleClassName2: {},
    hasFrame6: true,
    graphChartLineText46: "49.0%",
    graphChartLineText47: "49.0%",
    graphChartLineText48: "49.0%",
    graphChartLineSectionTitleClassName11: {},
    graphChartLineText49: "Refinery Source Tests",
    graphChartLineLines23: "two",
    graphChartLineColumns23: "three",
    graphChartLineText50: "49.0%",
    graphChartLineText51: "49.0%",
    graphChartLineText52: "Refinery Source Tests",
    graphChartLineLines24: "two",
    graphChartLineColumns24: "three",
    graphChartLineSectionTitleClassName12: {},
    graphChartTotalGraphChartLineSectionTitleClassName3: {},
    graphChartTotalGraphChartLineText7: "abc",
    graphChartTotalGraphChartLineFrameWrapperClassName: {},
    graphChartTotalLines4: "three",
    graphChartTotalGraphChartLineColumns4: "abc",
    graphChartTotalGraphChartLineFrameWrapperClassNameOverride: {},
    graphChartLineText53: "49.0%",
    graphChartLineText54: "49.0%",
    graphChartLineText55: "49.0%",
    graphChartLineText56: "49.0%",
    graphChartLineText57: "Refinery Source Tests",
    graphChartLineLines25: "two",
    graphChartLineColumns25: "three",
    graphChartLineSectionTitleClassName13: {},
    graphChartTotalGraphChartLineSectionTitleClassName4: {},
    graphChartTotalGraphChartLineText8: "abc",
    graphChartTotalGraphChartLineSectionTitleWrapperClassName: {},
    graphChartTotalLines5: "three",
    graphChartTotalGraphChartLineColumns5: "abc",
    graphChartTotalGraphChartLineFrameClassName2: {},
    hasFrame7: true,
    graphChartLineSectionTitleClassName14: {},
    graphChartLineSectionTitleClassName15: {},
    graphChartLineResolution6: "desktop",
    graphChartLineFrameClassName10: {},
    graphChartLineText58: "49.0%",
    graphChartLineResolution7: "desktop",
    graphChartLineResolution8: "desktop",
    visible50: true,
    graphChartLineResolution9: "desktop",
    graphChartTotalGraphChartLineHasDiv: true,
    graphChartTotalResolution: "desktop",
    graphChartTotalGraphChartLineText9: "abc",
    graphChartTotalGraphChartLineLinesColumnsClassName: {},
    graphChartTotalGraphChartLineSectionTitleClassName5: {},
    hasFrame8: true,
    graphChartLineResolution10: "desktop",
    visible51: true,
    graphChartTotalGraphChartLineFrameClassName3: {},
    hasFrame9: true,
    graphChartLineText59: "2,165",
    graphChartLineText60: "2,165",
    graphChartLineText61: "2,165",
    graphChartLineText62: "2,165",
    graphChartLineText63: "Refinery Source Tests",
    graphChartLineText64: "2,165",
    graphChartLineLines26: "two",
    graphChartLineText65: "49.0%",
    graphChartLineText66: "Refinery Source Tests",
    graphChartLineText67: "2,165",
    graphChartLineLines27: "two",
    graphChartLineText68: "49.0%",
    graphChartLineText69: "Refinery Source Tests",
    graphChartLineText70: "2,165",
    graphChartLineLines28: "two",
    graphChartLineText71: "49.0%",
    graphChartLineText72: "Refinery Source Tests",
    graphChartLineText73: "2,165",
    graphChartLineLines29: "two",
    graphChartLineText74: "49.0%",
    graphChartLineText75: "Refinery Source Tests",
    graphChartLineText76: "2,165",
    graphChartLineLines30: "two",
    graphChartLineText77: "49.0%",
    graphChartTotalGraphChartLineText10: "abc",
    graphChartTotalGraphChartLineFrameClassName4: {},
    graphChartTotalGraphChartLineLinesColumnsClassNameOverride: {},
    graphChartLineColumns26: "three",
    graphChartLineColumns27: "three",
    graphChartLineColumns28: "three",
    graphChartLineColumns29: "three",
    graphChartLineColumns30: "three",
    hasFrame10: true,
    visible52: true,
    visible53: true,
    visible54: true,
    graphChartTotalGraphChartLineSectionTitleClassName6: {},
    graphChartTotalGraphChartLineSectionTitleClassName7: {},
    graphChartTotalGraphChartLineText11: "abc",
    graphChartTotalGraphChartLineText12: "abc",
    graphChartTotalGraphChartLineText13: "abc",
    graphChartTotalGraphChartLineText14: "abc",
    graphChartTotalGraphChartLineVisible: true,
    graphChartTotalGraphChartLineHasFrame1: true,
    graphChartTotalGraphChartLineColumns6: "abc",
    graphChartLineFrameClassName11: {},
    graphChartLineSectionTitleClassName16: {},
    hasFrame11: true,
    graphChartLineText78: "2,165",
    graphChartLineText79: "2,165",
    graphChartLineText80: "2,165",
    graphChartLineText81: "2,165",
    graphChartLineText82: "Refinery Source Tests",
    graphChartLineText83: "2,165",
    graphChartLineLines31: "two",
    graphChartLineText84: "49.0%",
    graphChartLineText85: "Refinery Source Tests",
    graphChartLineText86: "2,165",
    graphChartLineLines32: "two",
    graphChartLineText87: "49.0%",
    graphChartLineText88: "Refinery Source Tests",
    graphChartLineText89: "2,165",
    graphChartLineLines33: "two",
    graphChartLineText90: "49.0%",
    graphChartLineText91: "Refinery Source Tests",
    graphChartLineText92: "2,165",
    graphChartLineLines34: "two",
    graphChartLineText93: "49.0%",
    graphChartLineText94: "Refinery Source Tests",
    graphChartLineText95: "2,165",
    graphChartLineLines35: "two",
    graphChartLineText96: "49.0%",
    graphChartTotalGraphChartLineText15: "abc",
    graphChartLineColumns31: "three",
    graphChartLineColumns32: "three",
    graphChartLineLinesColumnsClassName3: {},
    graphChartLineGraphChartLineClassName5: {},
    graphChartLineFrameClassName12: {},
    graphChartLineColumns33: "three",
    graphChartLineSectionTitleClassName17: {},
    graphChartLineColumns34: "three",
    graphChartLineColumns35: "three",
    graphChartTotalGraphChartLineText16: "abc",
    graphChartLineFrameClassName13: {},
    visible55: true,
    graphChartTotalGraphChartLineText17: "abc",
    graphChartTotalGraphChartLineSectionTitleClassName8: {},
    graphChartTotalGraphChartLineText18: "abc",
  },
};
