import { GraphChartTotal } from ".";

export default {
  title: "Components/GraphChartTotal",
  component: GraphChartTotal,
  argTypes: {
    lines: {
      options: ["two", "three", "one"],
      control: { type: "select" },
    },
    resolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    lines: "two",
    resolution: "desktop",
    className: {},
    graphChartLineGraphChartLineClassName: {},
    graphChartLineSectionTitleClassName: {},
    graphChartLineText: "TOTAL FUNDS AWARDED",
    graphChartLineHasFrame: true,
    graphChartLineSectionTitleClassNameOverride: {},
    graphChartLineColumns: "three",
    graphChartLineText1: "49.0%",
    graphChartLineFrameClassName: {},
    graphChartLineDivClassName: {},
    graphChartLineFrameClassNameOverride: {},
    graphChartLineDivClassNameOverride: {},
    graphChartLineLinesColumnsClassName: {},
    graphChartLineText2: "2,165",
    graphChartLineText3: "TOTAL FUNDS AWARDED",
    graphChartLineHasDiv: true,
    graphChartLineSectionTitleClassName1: {},
    graphChartLineColumns1: "three",
    graphChartLineText4: "49.0%",
    graphChartLineText5: "TOTAL FUNDS AWARDED",
    graphChartLineVisible: true,
    graphChartLineSectionTitleClassName2: {},
    graphChartLineText6: "49.0%",
    graphChartLineGraphChartLineClassNameOverride: {},
    graphChartLineText7: "TOTAL FUNDS AWARDED",
    graphChartLineSectionTitleClassName3: {},
    graphChartLineLinesColumnsClassNameOverride: {},
    graphChartLineHasSectionTitle: true,
    graphChartLineSectionTitleClassName4: {},
    graphChartLineText8: "2,165",
    graphChartLineFrameClassName1: {},
    visible: true,
    visible1: true,
    graphChartLineText9: "Total",
    graphChartLineText10: "Total",
    graphChartLineSectionTitleClassName5: {},
    graphChartLineText11: "Total",
    graphChartLineText12: "49.0%",
    graphChartLineFrameWrapperClassName: {},
    graphChartLineColumns2: "three",
    graphChartLineSectionTitleClassName6: {},
    graphChartLineText13: "Total",
    graphChartLineText14: "49.0%",
    graphChartLineFrameWrapperClassNameOverride: {},
    graphChartLineSectionTitleClassName7: {},
    graphChartLineText15: "Total",
    graphChartLineText16: "49.0%",
    graphChartLineFrameClassName2: {},
    graphChartLineSectionTitleClassName8: {},
    graphChartLineText17: "Total",
    graphChartLineSectionTitleClassName9: {},
    graphChartLineFrameClassName3: {},
    graphChartLineSectionTitleClassName10: {},
    graphChartLineFrameClassName4: {},
  },
};
