import { StatSection } from ".";

export default {
  title: "Components/StatSection",
  component: StatSection,
  argTypes: {
    resolution: {
      options: ["desktop", "mobile"],
      control: { type: "select" },
    },
    quantity: {
      options: ["two", "three"],
      control: { type: "select" },
    },
    aligment: {
      options: ["right", "centered"],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    resolution: "desktop",
    quantity: "two",
    aligment: "right",
    title: true,
    className: {},
    hasSectionTitle: true,
    statSetStatTypeNumbersColorClassName: {},
    statSetStatText: "$381M",
    statSetStatText1: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatText2: "$381M",
    statSetStatTypeNumbersColorClassNameOverride: {},
    statSetStatText3: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatType: "numbers",
    statSetStatColor: "white",
    statSetStatTypeQuoteColorClassName: {},
    statSetResolutionDesktopClassName: {},
    statSetStatColor1: "white",
    statSetStatTypeQuoteColorClassNameOverride: {},
    statSetStatSectionTitleClassName: {},
    statSetStatSectionTitleClassNameOverride: {},
    statSetStatText4: "$381M",
    statSetStatText5: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatDivClassName: {},
    statSetStatText6: "$381M",
    statSetStatText7: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatType1: "numbers",
    statSetStatColor2: "white",
    statSetStatDivClassNameOverride: {},
    statSetResolutionDesktopClassNameOverride: {},
    statSetStatColor3: "white",
    statSetStatText8: "$381M",
    statSetStatColor4: "white",
    statSetStatText9: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatText10: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatText11: "for Clean Cars For All Program and Clean School Bus Program",
    statSetStatTypeNumbersColorClassName1: {},
    statSetStatTypeNumbersColorClassName2: {},
    statSetStatText12: "$381M",
    statSetStatText13: "$381M",
    statSetStatColor5: "white",
    statSetStatSectionTitleClassName1: {},
    statSetStatSectionTitleClassName2: {},
    statSetStatText14: "abc",
    statSetStatText15: "$381M",
    statSetStatText16: "for Clean Cars For All Program and Clean School Bus Program",
  },
};
